In [30]:
import numpy as np
my_lst1 = [1,2,3,4,5]
my_lst2 = [2,3,4,5,6]
my_lst3 = [9,7,5,8,6]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [31]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 8, 6]])

In [32]:
arr.shape

(3, 5)

In [19]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [5, 8, 6]])

In [22]:
arr.reshape(3,5)

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 8, 6]])

In [23]:
arr.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [20]:
my_lst1 = [1,2,3,4,5,6,7,8]
my_lst2 = [2,3,4,5,6,7,8,9]
my_lst3 = [9,7,5,8,6,8,9,6]

arr1 = np.array([my_lst1,my_lst2,my_lst3])

In [21]:
arr1.reshape(6,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 5],
       [6, 7, 8, 9],
       [9, 7, 5, 8],
       [6, 8, 9, 6]])

## Indexing

In [33]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 8, 6]])

In [38]:
arr[2:,2:]

array([[5, 8, 6]])

In [51]:
arr[1:2,1:4]

array([[3, 4, 5]])

In [55]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr = np.arange(0,10,step=2)
arr

array([0, 2, 4, 6, 8])

In [58]:
arr = np.arange(0,10,step=3)
arr

array([0, 3, 6, 9])

In [65]:
arr = np.linspace(1,10,30)
arr

array([ 1.        ,  1.31034483,  1.62068966,  1.93103448,  2.24137931,
        2.55172414,  2.86206897,  3.17241379,  3.48275862,  3.79310345,
        4.10344828,  4.4137931 ,  4.72413793,  5.03448276,  5.34482759,
        5.65517241,  5.96551724,  6.27586207,  6.5862069 ,  6.89655172,
        7.20689655,  7.51724138,  7.82758621,  8.13793103,  8.44827586,
        8.75862069,  9.06896552,  9.37931034,  9.68965517, 10.        ])

In [78]:
arr1 = np.arange(0,15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [79]:
##copy

arr1[3:]=500

In [80]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500,
       500, 500])

In [81]:
arr1 = np.arange(0,15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [83]:
arr1[:2]=500
arr1

array([500, 500,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [90]:
val=6

arr1<6

array([False, False,  True,  True,  True,  True, False, False, False,
       False, False, False, False, False, False])

In [91]:
val=6

arr1*6

array([3000, 3000,   12,   18,   24,   30,   36,   42,   48,   54,   60,
         66,   72,   78,   84])

In [92]:
val=6

arr1/6

array([83.33333333, 83.33333333,  0.33333333,  0.5       ,  0.66666667,
        0.83333333,  1.        ,  1.16666667,  1.33333333,  1.5       ,
        1.66666667,  1.83333333,  2.        ,  2.16666667,  2.33333333])

In [93]:
val=6

arr1%6

array([2, 2, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2], dtype=int32)

In [94]:
np.ones(3)

array([1., 1., 1.])

In [100]:
np.ones((3,2),dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [98]:
np.zeros((5,2),dtype=float)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [103]:
np.random.rand(2,2)

array([[0.48391232, 0.074516  ],
       [0.84043356, 0.63412646]])